import type { Metadata } from "next";

import ClientRootLayout from "./client-root-layout";
import Providers from "./provider";
import { SessionData, sessionOptions } from "@/lib/utils/iron-session";
import { getIronSession } from "iron-session";
import { cookies } from "next/headers";
import { Toaster } from "react-hot-toast";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getIronSession<SessionData>(cookies(), sessionOptions);

  return (
    <html lang="pt-br">
      <body>
        <Providers defaultSession={JSON.parse(JSON.stringify(session))}>
          <ClientRootLayout>{children}</ClientRootLayout>
          <Toaster position="top-right" reverseOrder={false} />
        </Providers>
      </body>
    </html>
  );
}
